# Generated by Django 5.2.4 on 2025-10-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('Planes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Planes_app.plan'),
            preserve_default=False,
        ),
    ]
