# Generated by Django 5.0.2 on 2025-10-09 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0009_gasto_imagen_ingreso_imagen_objetivo_imagen_and_more'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Planes_app.plan'),
        ),
    ]
