# Generated by Django 5.2.4 on 2025-10-11 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dinero', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gasto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Dinero (Cuentas)',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=65535)),
                ('tipo_gasto', models.CharField(choices=[('alimentacion', 'Alimentación'), ('alquiler', 'Alquiler/Vivienda'), ('servicios', 'Servicios'), ('transporte', 'Transporte'), ('entretenimiento', 'Entretenimiento'), ('otro', 'Otro')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gastos/')),
                ('dinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Planes_app.dinero')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=65535)),
                ('tipo_ingreso', models.CharField(choices=[('salario', 'Salario'), ('inversion', 'Inversión'), ('extra', 'Ingreso Extra'), ('otro', 'Otro')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ingresos/')),
                ('dinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Planes_app.dinero')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=65535)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_plan', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='individual', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='planes/')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('detalles', models.TextField(max_length=65535)),
                ('monto_necesario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=50)),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='objetivos/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='Planes_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_invitacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='Planes_app.plan')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
            },
        ),
        migrations.AddField(
            model_name='dinero',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinero', to='Planes_app.plan'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=65535, null=True)),
                ('tipo_tarea', models.CharField(choices=[('pago', 'Pago'), ('recordatorio', 'Recordatorio'), ('tramite', 'Trámite'), ('otro', 'Otro')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tareas/')),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_a_completar', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=50)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Planes_app.plan')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea y Recordatorio',
                'verbose_name_plural': 'Tareas y Recordatorios',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.CharField(choices=[('miembro', 'Miembro'), ('moderador', 'Moderador'), ('admin', 'Admin')], default='miembro', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='Planes_app.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suscripciones',
                'unique_together': {('usuario', 'plan')},
            },
        ),
    ]
