# Generated by Django 4.0.6 on 2025-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='rol',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('moderador', 'Moderador'), ('admin', 'admin')], default='miembro', max_length=10),
        ),
    ]
