# Generated by Django 5.2.6 on 2025-09-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
