# Generated by Django 4.1.7 on 2025-09-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0002_ingreso_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tipo_plan',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='individual', max_length=10),
        ),
    ]
