# Generated by Django 5.2.6 on 2025-09-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0002_tarea_fecha_completado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea y Recordatorio', 'verbose_name_plural': 'Tareas y Recordatorios'},
        ),
    ]
