# Generated by Django 4.1.7 on 2025-09-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0003_plan_tipo_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('alquiler', 'Alquiler'), ('comida', 'Comida'), ('servicios', 'Servicios'), ('entretenimiento', 'Entretenimiento'), ('transporte', 'Transporte'), ('deuda', 'Deuda'), ('otro', 'Otro')], default='alquiler', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_ingreso',
            field=models.CharField(choices=[('salario', 'Salario'), ('ganancia', 'Ganancia'), ('venta', 'Venta'), ('regalo', 'Regalo'), ('otro', 'Otro')], default='salario', max_length=50),
        ),
    ]
