# Generated by Django 5.1.6 on 2025-10-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0003_alter_tarea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='rol',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('admin', 'Admin')], default='miembro', max_length=10),
        ),
    ]
