# Generated by Django 5.1.6 on 2025-09-26 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0004_alter_gasto_tipo_gasto_alter_ingreso_tipo_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='plan',
        ),
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(default='', max_length=65535),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_guardado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='descripcion',
            field=models.TextField(default='', max_length=65535),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_guardado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('alimentacion', 'Alimentación'), ('alquiler', 'Alquiler/Vivienda'), ('servicios', 'Servicios'), ('transporte', 'Transporte'), ('entretenimiento', 'Entretenimiento'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_ingreso',
            field=models.CharField(choices=[('salario', 'Salario'), ('inversion', 'Inversión'), ('extra', 'Ingreso Extra'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_suscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='Planes_app.plan'),
        ),
        migrations.CreateModel(
            name='Dinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dinero', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gasto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinero', to='Planes_app.plan')),
            ],
            options={
                'verbose_name_plural': 'Dinero (Cuentas)',
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='dinero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Planes_app.dinero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='dinero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Planes_app.dinero'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('detalles', models.TextField(max_length=65535)),
                ('monto_necesario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=50)),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='Planes_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=65535, null=True)),
                ('tipo_tarea', models.CharField(choices=[('pago', 'Pago'), ('recordatorio', 'Recordatorio'), ('tramite', 'Trámite'), ('otro', 'Otro')], max_length=50)),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_a_completar', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Planes_app.plan')),
            ],
        ),
    ]
