# Generated by Django 5.1.6 on 2025-10-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0005_invitacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitacion',
            unique_together=set(),
        ),
    ]
