# Generated by Django 5.2.4 on 2025-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0007_gasto_user_ingreso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes/'),
        ),
    ]
