# Generated by Django 5.2.4 on 2025-10-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes_app', '0008_plan_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gastos/'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ingresos/'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='objetivos/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tareas/'),
        ),
    ]
